name: bootstrap
channels:
  - defaults
  - conda-forge
dependencies:
  - arch-py=5.3.1
  - matplotlib=3.5.1
  - numba=0.53.0
  - numpy=1.22.3
  - pandas=1.4.3
  - python=3.9.12
  - scipy=1.9.0
  - seaborn=0.11.2
  - statsmodels=0.13.2
  - tqdm=4.64.0
  - rpy2=3.5.1